### ISSUE TITLE
Wrong Column Names in Output

### ISSUE THREAD

**Issue by matgrioni** [BramVanroy/spacy_conll#24]
First off thanks for this library. It fits some great use cases!

I am leveraging this to create conll output from stanza, and I notice that the column names don't actually match the [UD format spec](https://universaldependencies.org/format). Specifically, the names `xpostag`, and `upostag` are used instead of `xpos` and `upos`.

Understandably there's a bit of ambiguity here since this is spacy_conll and not spacy_conll*u* and I think the original conll formats did use xpostag and upostag, but the actual documentation refers frequently to the ConLL-U format, and I think is the only variant that has an actual spec for its format that can be adhered to.

This is all to say, an option to specify the column names would be very helpful at minimum. I'm not sure how the majority of downstream processing tools handle this, but it may also be helpful to have a flag that allows for "strict" adherence to the ConLL-U spec (to avoid the same duplication of official headers by different users) and if false use the existing column names as the legacy default.

**Comment by matgrioni** [comment]
Actually after quickly double checking, let me correct myself. Somehow I thought the header was required in the CoNLL format, but it isn't and there's no "official header". Either way I think allowing this to be modifiable would be useful since xpostag is not the official name of the column, but the strict/legacy flag would be inappropriate actually.

**Comment by BramVanroy** [comment]
The reason for the ambiguity is that this library simply formats the output of other models (any spaCy, Stanza, or UDPipe-compatible model). It is therefore not a given that the output of those models are indeed UD-compatible so I was hesitant to claim that the output is always CoNLL-U. But I understand your point from a user perspective that that can be confusing.

Supporting CoNLL-U Plus is not something I can make time for unfortunately. In fact, time permitting I would rather focus on building some good documentation and more examples and tests because supporting stanza, spaCy and UDPipe at the same time for different versions has proven challenging. But in any case, if I find the time on a weekend, I will address your comments. Probably both stream-lining the column names with CoNLL-U specifically and also allowing users to provide custom column names.

**Comment by BramVanroy** [comment]
Hi @matgrioni. In the new release the default CoNLL-U fields are used and you can now also override these defaults if you want to by using `field_names`. For instance, replacing the default "XPOS" by "cookies": 

```python
import spacy


nlp = spacy.load("en_core_web_sm")
config = {"field_names": {"XPOS": "cookies"}}
nlp.add_pipe("conll_formatter", config=config, last=True)
```

Hope that helps! I'm adding a separate topic as a feature request to support CoNLL-U Plus.

**Comment by matgrioni** [comment]
Thank you! Your points make perfect sense and configurable field names seem the best approach.

Also to be clear, my comment isn't necessarily a vote for supporting CoNLL-U Plus, rather that official documentation supports the column name changes. I have actually never seen such a file in the wild and I think tool support for it is pretty weak overall, so in your list of other priorities you mentioned, my vote would definitely be more tests and documentation :)
